name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-11-jdk python3-pip python3-setuptools python3-venv
        pip install Cython buildozer python-for-android

    - name: Initialize buildozer
      run: |
        buildozer init || true
        sed -i 's/requirements = python3/requirements = python3,kivy,gtts/' buildozer.spec
        sed -i 's/# android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: cj-assistant-apk
        path: bin/*.apk
